### ISSUE TITLE
swipe not working 

### ISSUE THREAD

**Issue by johnpaulmanoza** [cezarcp/swipe-tab-bar#1]
on the sample project, swipe functionality is not working on ios8.1.2

**Comment by davidstenstroem** [comment]
I can confirm this. It doesn't work in the sample project and doesn't work when implemented in other projects.

**Comment by cherishloveyou** [comment]
A Ha，I found the reason. Please take attention on swipe gesture, it's only work on tab-bar ,not tab-bar's controller. seems some userfull

**Comment by cezarcp** [comment]
Thank you all. @cherishloveyou is right. The gesture recognizer only works on the `UITabBar`, and that's the intended behavior.
